source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
target 'NewCommunity' do

pod 'AFNetworking', '~> 3.1.0'
pod 'MJRefresh', '~> 3.1.12'
pod 'SDCycleScrollView', '~> 1.73'
pod 'SVProgressHUD', '~> 2.2.1'
pod 'SDAutoLayout', '~> 2.2.0'
pod 'QMUIKit', '~> 2.0.0'
pod 'IQKeyboardManager', '~> 4.0.7'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'IQActionSheetPickerView', '~> 1.0.5'
pod 'JPush', '~> 3.0.6'
pod 'TZImagePickerController', '~> 1.9.3'
pod 'PYPhotoBrowser', '~> 1.5.2'
end
